spring:
  application:
    name: bootick

  datasource:
    url: jdbc:mysql://localhost:3306/bootick_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: srmzhk
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true